# NumPy Basics

Ten short exercises covering array creation, boolean masking, indexing tricks, and basic statistics with NumPy.

## Q1 — Create a 3x3 boolean array of all `True`

In [1]:

import numpy as np

arr = np.full((3, 3), True)
print(arr)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Q2 — Replace all odd numbers in an array with -1

In [2]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 == 1] = -1
print(arr)


[-1  2 -1  4 -1  6 -1  8 -1 10]


## Q3 — Intersection of two arrays

In [3]:

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
print(np.intersect1d(array1, array2))


[4 5]


## Q4 — Positions where two arrays have equal elements

In [4]:

a = np.array([1, 2, 3, 2, 4, 5])
b = np.array([1, 3, 3, 2, 4, 6])
print(np.where(a == b)[0])


[0 2 3 4]


## Q5 — Swap two columns in a 2D array

In [5]:

arr = np.array([[11, 12, 13],
                 [21, 22, 23],
                 [31, 32, 33]])
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)


[[12 11 13]
 [22 21 23]
 [32 31 33]]


## Q6 — Swap two rows in a 2D array

In [6]:

arr = np.array([[11, 12, 13],
                 [21, 22, 23],
                 [31, 32, 33]])
arr[[0, 1], :] = arr[[1, 0], :]
print(arr)


[[21 22 23]
 [11 12 13]
 [31 32 33]]


## Q7 — Reverse the columns of a 2D array

In [7]:

arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr[:, ::-1])


[[3 2 1]
 [6 5 4]
 [9 8 7]]


## Q8 — Reverse the rows of a 2D array

In [8]:

print(arr[::-1])


[[7 8 9]
 [4 5 6]
 [1 2 3]]


## Q9 — Round float values to 3 decimal places

In [9]:

arr = np.array([3.1415926, 2.7182818, 1.4142135])
print(np.round(arr, 3))


[3.142 2.718 1.414]


## Q10 — Mean, median, and standard deviation of an array

In [10]:

arr = np.array([10, 20, 30, 40, 50])
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Standard Deviation =", np.std(arr))


Mean = 30.0
Median = 30.0
Standard Deviation = 14.142135623730951
